<a href="https://colab.research.google.com/github/Pranq-lgtm/Data_Preparation/blob/main/Movie_Theatre.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv("/movie theatre.csv")

In [ ]:
data.head()

,Timestamp,Which genres of movie do you like the most?,Which movie theatre do you like visiting the most,How many movie have you are in past three months in movie theatre,Do you like to buy beverages and popcorns from movie theatre,In which row do you like to sit and watch movie,Your take on should there be more movie theatres in your locality or not,Do you like to watch movie with friends and family or alone,If you have watched the recent movie 'kalki 2898 AD' give your review about the movie,Describe your reaction after first visiting a movie theatre,Do you like to watch 3D movies(if yes describe your reaction)
0,2024/07/11 11:39:07 am GMT+5:30,Horror,Inox,4.0,No,Premium row,No,Friends and family,Flop,Shouting at the climax,No
1,2024/07/11 11:40:19 am GMT+5:30,Thriller,Pvr,5.0,No,Middle row;Premium row,Maybe,Special person,Movie story at starting is lil boring but endi...,Came in different planet only,Yes 3D movies experience and feeling are real
2,2024/07/11 11:46:55 am GMT+5:30,Drama,Inox,1.0,No,Middle row;Premium row,Maybe,Friends and family,It’s good and etc n all,It’s was a good experience,I don’t watch 3d movies
3,2024/07/18 9:42:23 am GMT+5:30,Horror,Inox,1.0,Yes,Back row;Premium row,Maybe,Alone,it was good,Awesome,Yes
4,2024/07/11 11:39:07 am GMT+5:30,Horror,Inox,6.0,No,Premium row,No,Friends and family,Flop,Shouting at the climax,No

In [ ]:
data.sample(10)

,Timestamp,Which genres of movie do you like the most?,Which movie theatre do you like visiting the most,How many movie have you are in past three months in movie theatre,Do you like to buy beverages and popcorns from movie theatre,In which row do you like to sit and watch movie,Your take on should there be more movie theatres in your locality or not,Do you like to watch movie with friends and family or alone,If you have watched the recent movie 'kalki 2898 AD' give your review about the movie,Describe your reaction after first visiting a movie theatre,Do you like to watch 3D movies(if yes describe your reaction)
16,2024/07/11 11:39:07 am GMT+5:30,Horror,Inox,7.0,No,Premium row,No,Friends and family,Flop,Shouting at the climax,No
15,2024/07/18 9:42:23 am GMT+5:30,Horror,Inox,2.0,Yes,Back row;Premium row,Maybe,Alone,it was good,Awesome,Yes
8,2024/07/11 11:39:07 am GMT+5:30,Horror,Inox,4.0,No,Premium row,No,Friends and family,Flop,Shouting at the climax,No
14,2024/07/11 11:46:55 am GMT+5:30,Drama,Inox,2.0,No,Middle row;Premium row,Maybe,Friends and family,It’s good and etc n all,It’s was a good experience,I don’t watch 3d movies
2,2024/07/11 11:46:55 am GMT+5:30,Drama,Inox,1.0,No,Middle row;Premium row,Maybe,Friends and family,It’s good and etc n all,It’s was a good experience,I don’t watch 3d movies
23,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2024/07/11 11:39:07 am GMT+5:30,Horror,Inox,3.0,No,Premium row,No,Friends and family,Flop,Shouting at the climax,No
4,2024/07/11 11:39:07 am GMT+5:30,Horror,Inox,6.0,No,Premium row,No,Friends and family,Flop,Shouting at the climax,No
21,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2024/07/11 11:46:55 am GMT+5:30,Drama,Inox,1.0,No,Middle row;Premium row,Maybe,Friends and family,It’s good and etc n all,It’s was a good experience,I don’t watch 3d movies

In [ ]:
data.columns

Index(['Timestamp', 'Which genres of movie do you like the most?',
       'Which movie theatre do you like visiting the most ',
       'How many movie have you are in past three months in movie theatre ',
       'Do  you like to buy beverages and popcorns from movie theatre ',
       'In which row do you like to sit and watch movie ',
       'Your take on should there be more movie theatres in your locality or not ',
       'Do you like to watch movie with friends and family or alone',
       'If you have watched the recent movie 'kalki 2898 AD' give your review about the movie ',
       'Describe your reaction after first visiting a movie theatre ',
       'Do you like to watch 3D movies(if yes describe your reaction)'],
      dtype='object')

In [ ]:
data.shape

(26, 11)

In [ ]:
print(data)

                          Timestamp  \
0   2024/07/11 11:39:07 am GMT+5:30
1   2024/07/11 11:40:19 am GMT+5:30
2   2024/07/11 11:46:55 am GMT+5:30
3    2024/07/18 9:42:23 am GMT+5:30
4   2024/07/11 11:39:07 am GMT+5:30
5   2024/07/11 11:40:19 am GMT+5:30
6   2024/07/11 11:46:55 am GMT+5:30
7    2024/07/18 9:42:23 am GMT+5:30
8   2024/07/11 11:39:07 am GMT+5:30
9   2024/07/11 11:40:19 am GMT+5:30
10  2024/07/11 11:46:55 am GMT+5:30
11   2024/07/18 9:42:23 am GMT+5:30
12  2024/07/11 11:39:07 am GMT+5:30
13  2024/07/11 11:40:19 am GMT+5:30
14  2024/07/11 11:46:55 am GMT+5:30
15   2024/07/18 9:42:23 am GMT+5:30
16  2024/07/11 11:39:07 am GMT+5:30
17  2024/07/11 11:40:19 am GMT+5:30
18  2024/07/11 11:46:55 am GMT+5:30
19                              NaN
20                              NaN
21                              NaN
22                              NaN
23                              NaN
24                              NaN
25                              NaN

   Which genres of movie do you like the most?  \
0                                       Horror
1                                     Thriller
2                                        Drama
3                                       Horror
4                                       Horror
5                                     Thriller
6                                        Drama
7                                       Horror
8                                       Horror
9                                     Thriller
10                                       Drama
11                                      Horror
12                                      Horror
13                                    Thriller
14                                       Drama
15                                      Horror
16                                      Horror
17                                    Thriller
18                                       Drama
19                                         NaN
20                                         NaN
21                                         NaN
22                                         NaN
23                                         NaN
24                                         NaN
25                                         NaN

   Which movie theatre do you like visiting the most   \
0                                                Inox
1                                                 Pvr
2                                                Inox
3                                                Inox
4                                                Inox
5                                                 Pvr
6                                                Inox
7                                                Inox
8                                                Inox
9                                                 Pvr
10                                               Inox
11                                               Inox
12                                               Inox
13                                                Pvr
14                                               Inox
15                                               Inox
16                                               Inox
17                                                Pvr
18                                               Inox
19                                                NaN
20                                                NaN
21                                                NaN
22                                                NaN
23                                                NaN
24                                                NaN
25                                                NaN

    How many movie have you are in past three months in movie theatre   \
0                                            4.000000
1                                            5.000000
2                                            1.000000
3                                            1.000000
4                                            6.000000
5                                            4.000000
6                                            1.000000
7                                            1.000000
8                                            4.000000
9                                            6.000000
10                                           1.000000
11                                           2.000000
12                                           3.000000
13                                           5.000000
14                                           2.000000
15                                           2.000000
16                                           7.000000
17                                           6.000000
18                                           1.000000
19                                           3.263158
20                                                NaN
21                                           3.000000
22                                                NaN
23                                           1.000000
24                                                NaN
25                                           2.104020

   Do  you like to buy beverages and popcorns from movie theatre   \
0                                                  No
1                                                  No
2                                                  No
3                                                 Yes
4                                                  No
5                                                  No
6                                                  No
7                                                 Yes
8                                                  No
9                                                  No
10                                                 No
11                                                Yes
12                                                 No
13                                                 No
14                                                 No
15                                                Yes
16                                                 No
17                                                 No
18                                                 No
19                                                NaN
20                                                NaN
21                                                NaN
22                                                NaN
23                                                NaN
24                                                NaN
25                                                NaN

   In which row do you like to sit and watch movie   \
0                                       Premium row
1                            Middle row;Premium row
2                            Middle row;Premium row
3                              Back row;Premium row
4                                       Premium row
5                            Middle row;Premium row
6                            Middle row;Premium row
7                              Back row;Premium row
8                                       Premium row
9                            Middle row;Premium row
10                           Middle row;Premium row
11                             Back row;Premium row
12                                      Premium row
13                           Middle row;Premium row
14                           Middle row;Premium row
15                             Back row;Premium row
16                                      Premium row
17                           Middle row;Premium row
18                           Middle row;Premium row
19                                              NaN
20                                              NaN
21                                              NaN
22                                              NaN
23                                              NaN
24                                              NaN
25                                              NaN

   Your take on should there be more movie theatres in your locality or not   \
0                                                  No
1                                               Maybe
2                                               Maybe
3                                               Maybe
4                                                  No
5                                               Maybe
6                                               Maybe
7                                               Maybe
8                                                  No
9                                               Maybe
10                                              Maybe
11                                              Maybe
12                                                 No
13                                              Maybe
14                                              Maybe
15                                              Maybe
16                                                 No
17                                              Maybe
18                                              Maybe
19                                                NaN
20                                                NaN
21                                                NaN
22                                                NaN
23                                                NaN
24                                                NaN
25                                                NaN

   Do you like to watch movie with friends and family or alone  \
0                                  Friends and family
1                                     Special person
2                                  Friends and family
3                                               Alone
4                                  Friends and family
5                                     Special person
6                                  Friends and family
7                                               Alone
8                                  Friends and family
9                                     Special person
10                                 Friends and family
11                                              Alone
12                                 Friends and family
13                                    Special person
14                                 Friends and family
15                                              Alone
16                                 Friends and family
17                                    Special person
18                                 Friends and family
19                                                NaN
20                                                NaN
21                                                NaN
22                                                NaN
23                                                NaN
24                                                NaN
25                                                NaN

   If you have watched the recent movie 'kalki 2898 AD' give your review about the movie   \
0                                                Flop
1   Movie story at starting is lil boring but endi...
2                             It’s good and etc n all
3                                         it was good
4                                                Flop
5   Movie story at starting is lil boring but endi...
6                             It’s good and etc n all
7                                         it was good
8                                                Flop
9   Movie story at starting is lil boring but endi...
10                            It’s good and etc n all
11                                        it was good
12                                               Flop
13  Movie story at starting is lil boring but endi...
14                            It’s good and etc n all
15                                        it was good
16                                               Flop
17  Movie story at starting is lil boring but endi...
18                            It’s good and etc n all
19                                                NaN
20                                                NaN
21                                                NaN
22                                                NaN
23                                                NaN
24                                                NaN
25                                                NaN

   Describe your reaction after first visiting a movie theatre   \
0                              Shouting at the climax
1                      Came in different planet only
2                         It’s was a good experience
3                                            Awesome
4                              Shouting at the climax
5                      Came in different planet only
6                         It’s was a good experience
7                                            Awesome
8                              Shouting at the climax
9                      Came in different planet only
10                        It’s was a good experience
11                                           Awesome
12                             Shouting at the climax
13                     Came in different planet only
14                        It’s was a good experience
15                                           Awesome
16                             Shouting at the climax
17                     Came in different planet only
18                        It’s was a good experience
19                                                NaN
20                                                NaN
21                                                NaN
22                                                NaN
23                                                NaN
24                                                NaN
25                                                NaN

   Do you like to watch 3D movies(if yes describe your reaction)
0                                                  No
1      Yes 3D movies experience and feeling are real
2                            I don’t watch 3d movies
3                                                Yes
4                                                  No
5      Yes 3D movies experience and feeling are real
6                            I don’t watch 3d movies
7                                                Yes
8                                                  No
9      Yes 3D movies experience and feeling are real
10                           I don’t watch 3d movies
11                                               Yes
12                                                 No
13     Yes 3D movies experience and feeling are real
14                           I don’t watch 3d movies
15                                               Yes
16                                                 No
17     Yes 3D movies experience and feeling are real
18                           I don’t watch 3d movies
19                                                NaN
20                                                NaN
21                                                NaN
22                                                NaN
23                                                NaN
24                                                NaN
25                                                NaN

In [ ]:
print(data[5:10])

                         Timestamp  \
5  2024/07/11 11:40:19 am GMT+5:30
6  2024/07/11 11:46:55 am GMT+5:30
7   2024/07/18 9:42:23 am GMT+5:30
8  2024/07/11 11:39:07 am GMT+5:30
9  2024/07/11 11:40:19 am GMT+5:30

  Which genres of movie do you like the most?  \
5                                    Thriller
6                                       Drama
7                                      Horror
8                                      Horror
9                                    Thriller

  Which movie theatre do you like visiting the most   \
5                                                Pvr
6                                               Inox
7                                               Inox
8                                               Inox
9                                                Pvr

   How many movie have you are in past three months in movie theatre   \
5                                                4.0
6                                                1.0
7                                                1.0
8                                                4.0
9                                                6.0

  Do  you like to buy beverages and popcorns from movie theatre   \
5                                                 No
6                                                 No
7                                                Yes
8                                                 No
9                                                 No

  In which row do you like to sit and watch movie   \
5                           Middle row;Premium row
6                           Middle row;Premium row
7                             Back row;Premium row
8                                      Premium row
9                           Middle row;Premium row

  Your take on should there be more movie theatres in your locality or not   \
5                                              Maybe
6                                              Maybe
7                                              Maybe
8                                                 No
9                                              Maybe

  Do you like to watch movie with friends and family or alone  \
5                                    Special person
6                                 Friends and family
7                                              Alone
8                                 Friends and family
9                                    Special person

  If you have watched the recent movie 'kalki 2898 AD' give your review about the movie   \
5  Movie story at starting is lil boring but endi...
6                            It’s good and etc n all
7                                        it was good
8                                               Flop
9  Movie story at starting is lil boring but endi...

  Describe your reaction after first visiting a movie theatre   \
5                     Came in different planet only
6                        It’s was a good experience
7                                           Awesome
8                             Shouting at the climax
9                     Came in different planet only

  Do you like to watch 3D movies(if yes describe your reaction)
5     Yes 3D movies experience and feeling are real
6                           I don’t watch 3d movies
7                                               Yes
8                                                 No
9     Yes 3D movies experience and feeling are real

In [3]:
data=['columns_count']